#!/bin/bash

# Attempt to install curl.
sudo apt install --assume-yes curl
sudo pacman -Syu curl

# Install Hack Nerd font.
if [ ! "$1" == '--no-download' ]; then
	curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hack.zip
	sudo mkdir -p /usr/share/fonts/truetype/hacknerd
	sudo unzip -o Hack.zip -d /usr/share/fonts/truetype/hacknerd
	sudo fc-cache -fv
	rm -v Hack.zip
fi

# Install the latest neovim appimage.
nvim_path="/usr/local/bin/nvim.appimage"
if [ ! "$1" == '--no-download' ]; then
	sudo rm -v "${nvim_path}"
	sudo curl -Lo "${nvim_path}" https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
fi
sudo chmod +x "${nvim_path}"
#set -u
sudo update-alternatives --install /usr/bin/nvim nvim "${nvim_path}" 110

# Install the plugin manager.
if [ ! "$1" == '--no-download' ]; then
	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

nvim_config_directory_path="$HOME/.config/nvim"

# Backup old config directory.
sudo rm -rv "${nvim_config_directory_path}.backup" 
mv -v "${nvim_config_directory_path}" "${nvim_config_directory_path}.backup" 

# Copy the first part of init.vim to its proper location.
mkdir -p "${nvim_config_directory_path}"
cp -v 1.init.vim "${nvim_config_directory_path}"/init.vim

# Copy newcode config directory to its proper location.
cp -rv config "${nvim_config_directory_path}"/newcode

# Install plugins.
nvim +PlugInstall +qall

# Append the remaining part(s) of init.vim to the init.vim in the proper location.
cat 2.init.vim >> "${nvim_config_directory_path}"/init.vim

echo "newcode installed."
