-- require 'nvim-treesitter.configs'.setup { ... }
--
-- local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
--
-- vim.filetype.add({
--     pattern = {
--         [".*%.blade%.php"] = "blade",
--     },
-- })
--
-- parser_config.blade = {
--     install_info = {
--         url = "https://github.com/EmranMR/tree-sitter-blade",
--         files = { "src/parser.c" },
--         branch = "main",
--     },
--     filetype = "blade",
-- }
